# Generated by Django 2.1.2 on 2018-10-03 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockPile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='stocks',
            old_name='user_id',
            new_name='stock_id',
        ),
        migrations.AddField(
            model_name='stockpile',
            name='stock_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockApp.Stocks'),
        ),
        migrations.AddField(
            model_name='stockpile',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stockApp.Users'),
        ),
    ]
