# Generated by Django 2.1.2 on 2018-10-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0002_auto_20181003_0358'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpile',
            name='name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
