# Generated by Django 2.1.2 on 2018-10-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stockApp', '0003_stockpile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockpile',
            name='s_id',
            field=models.CharField(default='0000000', max_length=25),
        ),
    ]
